name: Release

on:
  push:
    branches:
      - master

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Set up Git
        run: |
          git config --global user.name 'JonathanR'
          git config --global user.email 'j.recly@gmail.com'

      - name: Extract version from composer.json
        id: get_version
        run: echo "::set-output name=VERSION::$(jq -r .version composer.json)"

      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ steps.get_version.outputs.VERSION }}
          git tag "v$VERSION"
          git push origin "v$VERSION"
